### ISSUE TITLE
Minor naming issue

### ISSUE THREAD

**Issue by mys31f** [cat-milk/Anime-Girls-Holding-Programming-Books#383] opened 2022-03-18 01:29 UTC
[Picture](https://github.com/cat-milk/Anime-Girls-Holding-Programming-Books/blob/master/Design%20Patterns/Girl_From_Random_Art_Holds_THe_Art_Of_Computer_Programming.png)
The girl in here is Rina Tennoji from Love Live, more specifically in Nijigasaki.

**Comment by asheeeshh** [comment] 2022-03-18 09:21
opening a pr to rename it as no one else seems to have done it yet.

**Comment by Kholodets** [comment] 2022-03-21 02:56
closing, that file is a duplicate of this anyways https://github.com/cat-milk/Anime-Girls-Holding-Programming-Books/blob/master/Algorithms/Rina_Tennoji_Holds_Russian_The_Art_Of_Computer_Programming.png

**Closed by Kholodets** 2022-03-21 02:56 UTC
