### ISSUE TITLE
Making additional metadata available

### ISSUE THREAD

**Issue by karai17** [cat-milk/Anime-Girls-Holding-Programming-Books#485] opened 2022-06-28 02:45 UTC
Are there any thoughts or opinions on making additional metadata available, one way or another? Currently, all of the images are separated into categorical (programming language) directories. Filenames do have some information such as character name, but the formatting of filenames is not easily parsable.

The goal would be to have metadata that would allow for a more interesting API to serve this collection of data. For example, find images based on a character rather than on a programming language or book title.

Some ideas:

* manually maintain a JSON file that provides metadata about each image (e.g. character name, image category, proper book title), to be updated with each PR
* adjust filename format to be more parsable (e.g. character-name_category_book-title.ext -> arikawa-hime_c_the-c-programming-language.jpg)

If there is a desire to provide more useful information, perhaps we could come up with exactly what information would be desirable?

* Category
* Character
* Book Title
* Source (Anime/Manga)
* etc

Edit: Looks like #276 already touched on this. Any further considerations since then?

**Comment by Kholodets** [comment] 2022-09-24 17:58
effective duplicate of #245, cleaning up issues

**Closed by Kholodets** 2022-09-24 17:58 UTC
